lein: lein2
language: clojure
script:
    - lein2 bikeshed
    - lein2 cljfmt check
    - lein2 kibit
    - lein2 cljsbuild once dev
    - lein2 cljsbuild once prod
    - lein2 cljsbuild test
notifications:
    email:
        - tech+travis.ona.io
    slack: onaio:snkNXgprD498qQv4DgRREKJF
